all: exercises02.pdf exercises02_solution.pdf \
	exercises03.pdf exercises03_solution.pdf \
	exercises04.pdf exercises04_solution.pdf \
	exercises05.pdf exercises05_solution.pdf \
	exercises06.pdf exercises06_solution.pdf \
	exercises06.pdf exercises06_solution.pdf \
	exercises07.pdf exercises07_solution.pdf \
	exercises08.pdf exercises08_solution.pdf \
	exercises09.pdf exercises09_solution.pdf \
	exercises10.pdf exercises10_solution.pdf \
	exercises11.pdf exercises11_solution.pdf	

exercises02.pdf: w02/exercises02.md w02/questions/*.md
	pushd w02; pandoc -f markdown --filter pandoc-include -o ../exercises02.pdf exercises02.md; popd;

exercises02_solution.pdf: w02/exercises02_solution.md w02/questions/*.md
	pushd w02; pandoc -f markdown -o ../exercises02_solution.pdf --filter pandoc-include exercises02_solution.md; popd;

exercises03.pdf: w03/exercises03.md w03/questions/*.md
	pushd w03; pandoc -f markdown --filter pandoc-include -o ../exercises03.pdf exercises03.md; popd;

exercises03_solution.pdf: w03/exercises03_solution.md w03/questions/*.md
	pushd w03; pandoc -f markdown -o ../exercises03_solution.pdf --filter pandoc-include exercises03_solution.md; popd;

exercises04.pdf: w04/exercises04.md w04/questions/*.md
	pushd w04; pandoc -f markdown --filter pandoc-include -o ../exercises04.pdf exercises04.md; popd;

exercises04_solution.pdf: w04/exercises04_solution.md w04/questions/*.md
	pushd w04; pandoc -f markdown -o ../exercises04_solution.pdf --filter pandoc-include exercises04_solution.md; popd;

exercises05.pdf: w05/exercises05.md w05/questions/*.md
	pushd w05; pandoc -f markdown --filter pandoc-include -o ../exercises05.pdf exercises05.md; popd;

exercises05_solution.pdf: w05/exercises05_solution.md w05/questions/*.md
	pushd w05; pandoc -f markdown -o ../exercises05_solution.pdf --filter pandoc-include exercises05_solution.md; popd;

exercises06.pdf: w06/exercises06.md w06/questions/*.md
	pushd w06; pandoc -f markdown --filter pandoc-include -o ../exercises06.pdf exercises06.md; popd;

exercises06_solution.pdf: w06/exercises06_solution.md w06/questions/*.md
	pushd w06; pandoc -f markdown --filter pandoc-include -o ../exercises06_solution.pdf  exercises06_solution.md; popd;

exercises07.pdf: w07/exercises07.md w07/questions/*.md
	pushd w07; pandoc -f markdown --filter pandoc-include -o ../exercises07.pdf exercises07.md; popd;

exercises07_solution.pdf: w07/exercises07_solution.md w07/questions/*.md
	pushd w07; pandoc -f markdown --filter pandoc-include -o ../exercises07_solution.pdf  exercises07_solution.md; popd;

exercises08.pdf: w08/exercises08.md w08/questions/*.md
	pushd w08; pandoc -f markdown --filter pandoc-include -o ../exercises08.pdf exercises08.md; popd;

exercises08_solution.pdf: w08/exercises08_solution.md w08/questions/*.md
	pushd w08; pandoc -f markdown --filter pandoc-include -o ../exercises08_solution.pdf  exercises08_solution.md; popd;

exercises09.pdf: w09/exercises09.md w09/questions/*.md
	pushd w09; pandoc -f markdown --filter pandoc-include -o ../exercises09.pdf exercises09.md; popd;

exercises09_solution.pdf: w09/exercises09_solution.md w09/questions/*.md
	pushd w09; pandoc -f markdown --filter pandoc-include -o ../exercises09_solution.pdf  exercises09_solution.md; popd;

exercises10.pdf: w10/exercises10.md w10/questions/*.md
	pushd w10; pandoc -f markdown --filter pandoc-include -o ../exercises10.pdf exercises10.md; popd;

exercises10_solution.pdf: w10/exercises10_solution.md w10/questions/*.md
	pushd w10; pandoc -f markdown --filter pandoc-include -o ../exercises10_solution.pdf  exercises10_solution.md; popd;

exercises11.pdf: w11/exercises11.md w11/questions/*.md
	pushd w11; pandoc -f markdown --filter pandoc-include -o ../exercises11.pdf exercises11.md; popd;

exercises11_solution.pdf: w11/exercises11_solution.md w11/questions/*.md
	pushd w11; pandoc -f markdown --filter pandoc-include -o ../exercises11_solution.pdf  exercises11_solution.md; popd;