project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "CSC477 - Fall 2024"
  description: "Homepage for CSC477/CSC2630: Introduction to Mobile Robotics, Fall 2024"
  site-url: "https://csc477.github.io/website_fall24"

  repo-url: https://github.com/csc477/website_fall24
  repo-actions: [issue]

  open-graph: true

  twitter-card:
    card-style: "summary" 

  page-footer:
    right: "This page is built with ❤️, [Quarto](https://quarto.org/) and inspiration from [STA210](https://sta210-s22.github.io/website/)."
    left: "&copy; Copyright 2024, Florian Shkurti"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/mars-exploration-rover.png"
    pinned: true
    align: center
    title: "CSC477/CSC2630 Introduction to Mobile Robotics"
    
    tools:
      - icon: github
        href: https://github.com/csc477 
        text: "Github workspace for the course"
      - icon: chat-quote
        href: http://piazza.com/utoronto.ca/fall2022/csc477
        text: "Discuss on Piazza"
      - icon: megaphone
        href: http://toolboxrenewal.utoronto.ca/
        text: "Official announcements on Quercus"
      - icon: envelope-at
        href: course-team.html
        text: "Email teaching staff"
   	
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: http://piazza.com/utoronto.ca/fall2022/csc477
        text: Piazza
      - href: http://toolboxrenewal.utoronto.ca/
        text: Quercus	
      # - href: course-syllabus.qmd
      #   text: Syllabus
      - href: course-team.qmd
        text: Teaching Staff
      - href: course-schedule.qmd
        text: Schedule
      # - href: project-description.qmd
      #   text: Final Project
      
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    
freeze: auto

editor: visual
script: [/lecs/w01/custom.js]