project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "CSC413 - Fall 2024, UTM"
  description: "Homepage for CSC413 - Neural Networks and Deep Learning, Fall 2024, UTM."
  site-url: "https://utm-csc413.github.io/2024F-website/"

  repo-url: https://github.com/utm-csc413/2024F-website
  repo-actions: [issue]

  open-graph: true

  twitter-card:
    card-style: "summary" 

  page-footer:
    right: "This page is built with ❤️, [Quarto](https://quarto.org/) and inspiration from [STA210](https://sta210-s22.github.io/website/)."
    left: "&copy; Copyright 2024, Florian Shkurti"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/neural_network.jpg"
    pinned: true
    align: center
    title: "UTM - CSC413 Neural Networks and Deep Learning"
    
    tools:
      - icon: github
        href: https://github.com/utm-csc413 
        text: "Github workspace for the course"
      - icon: chat-quote
        href: https://piazza.com/utoronto.ca/fall2024/csc413h5flec0101/home
        text: "Discuss on Piazza"
      - icon: megaphone
        href: https://q.utoronto.ca/courses/366713
        text: "Official announcements on Quercus"
      - icon: envelope-at
        href: course-team.html
        text: "Email teaching staff"
   	
        
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - href: https://piazza.com/utoronto.ca/fall2024/csc413h5flec0101/home
        text: Piazza
      - href: https://q.utoronto.ca/courses/366713
        text: Quercus	
      - href: course-syllabus.qmd
        text: Syllabus
      - href: course-team.qmd
        text: Teaching Staff
      - href: course-schedule.qmd
        text: Schedule
      - href: project-description.qmd
        text: Final Project
      
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    
freeze: auto

editor: visual
script: [/lecs/w01/custom.js]