---
title: "Grading Scheme"
---

|                            |                                               |
|----------------------------|-----------------------------------------------|
| Assignment 1            |          15%              |
| Assignment 2            |          15%              |
| Panel Discussion        |          10%              |
| Project Proposal        |          10%              |
| Project Presentation    |          25%              |
| Final Project Report    |          25%              |



### Marking rubric for panel discussion

Every week we will reserve 20-30 mins for a panel discussion based on the assigned reading for that day (4-5 papers).
This discussion will include three types of roles: panel members, audience members, and a moderator. Each panel discussion
will include 4 panel members, 1 moderator, and audience members. Panel members are responsible for answering questions,
the audience is responsible for asking questions, and the moderator is responsible for steering the discussion and having
backup questions if the audience is not asking any.  

#### Panel member evaluation

* Answering questions from the moderator and the audience correctly / well (6 pts)
* Engaging with points of other panelists (1 pts)
* Keeping answers brief / allowing other people time to speak (2 pts)
* Pre-submitting 1-2 questions on Quercus about the assigned papers of the day, the Thursday before lecture (1 pts)

#### Audience member evaluation
* Pre-submitting 1-2 questions on Quercus about the assigned papers of the day, the Thursday before lecture (10 pts)

#### Moderator evaluation

* Steering the discussion in terms of groups / themes of questions (2 pts)
* Ensuring there is time for every panel member to speak (4 pts)
* Engaging the audience / ensuring the audience has enough time to ask questions (3 pts) 
* Pre-submitting 1-2 questions on Quercus about the assigned papers of the day, the Thursday before lecture (1 pts)



### Marking rubric for the project proposal

* Introduction (1 pts), which states the proposed problem being solved and any applications / implications.
* Figure or diagram (1 pts), showing an overview of your proposed solution, i.e. shows the overall idea in a way that is easily understandable without even reading the rest of the report.
* Related work (1 pts) and bibliography. Highlight how your method is different from other approaches.
          Present other approaches in the proper light without diminishing their contributions.
* Methodology (2 pts). Describe your proposed methodology as well as any assumptions it relies on. Explain
prerequisite concepts clearly and succinctly. 
* Evaluation (2 pts). What experiments are you planning to do and why? What are the questions you want to answer through these experiments?
* Timeline (1 pts). What are the milestones required to complete your project and by when do you plan to complete them?
* Anticipated risks and mitigation plan (2 pts). What issues might arise with your proposed project and timeline and how will you address these issues if they occur?

### Marking rubric for the project presentation

#### Quality of presentation
* Slide design (2 pts)
* Delivery of presentation (3 pts)
* Respecting time constraints (2 pts)
* Response to questions (3 pts)

#### Technical content
* Motivation and definition of the problem (2 pts)
* Putting prior work into context (3 pts)
* Methodology explanation (3 pts)
* Discussion of experiments (5 pts)
* Discussion of limitations (2 pts)

### Marking rubric for the final project report


* Abstract (2 pts) that summarizes the main idea of the project and your contributions.
* Introduction (3 pts) that states the problem being solved and any applications / implications.
* Figure or diagram (2 pts) that shows the overall idea in a way that is easily understandable.
* Related work (2 pts) and bibliography. Highlight how your method is different from other approaches.
          Present other approaches in the proper light without diminishing their contributions.
* Methodology (7 pts). Describe your method in detail as well as any assumptions it relies on. Explain
prerequisite concepts clearly and succinctly. Include algorithm descriptions, figures, and equations as you
wish.
* Evaluation (8 pts). Include any figures or tables that illustrate your experimental results. Do not forget to include error bars if applicable. Analyze your findings, and comment on their statistical significance. In your
evaluation please take into account [Joelle Pineau's ML reproducibility checklist](https://www.cs.mcgill.ca/~jpineau/ReproducibilityChecklist.pdf).
* Limitations (2 pts). Describe some settings in which your approach performs poorly, and list a few ideas for
how to adddress them. Describe opportunities for future work, as well as open problems.
* Conclusions (1 pts). A summary of your contributions and results.