---
title: "Fall 2024 - CSC477/CSC2630: Introduction to Mobile Robotics"
tbl-colwidths: [5,10,30,5,5,5,5,5,5,5]
---

This page contains an outline of the topics, content, and assignments for the semester. Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-screen-inset-right
| Week | Date | Topic | Tutorial | Slides | Code | Assignments | Project |
|:-------:|---------|---------|:-------:|:-------:|:-------:|:-------:|:-------:|
| [1](#week-1) | Sep 14 | Introduction |  | [🖥️](/lecs/w01/lec01.html){.no-style target="_blank" aria-label="Lec 1 slides"} |  |  |  |
|  |  | Sensors and Actuators |  |  |  |  |  |
| [2](#week-2) | Sep 21 | Kinematics | [📖](/tutorials/w02/tut02.html){.no-style target="_blank" aria-label="Tut 2 slides"} | [🖥️](/lecs/w02/lec02.html){.no-style target="_blank" aria-label="Lec 2 slides"} |  |  |  |
|  |  | Dynamics |  |  |  |  |  |
| [3](#week-3) | Sep 28 | PID Control | [📖](/tutorials/w03/tut03.html){.no-style target="_blank" aria-label="Tut 3 slides"} | [🖥️](/lecs/w03/lec03.html){.no-style target="_blank" aria-label="Lec 3 slides"} |  |  |  |
|  |  | Artificial Potential Fields and Obstacle Avoidance |  |  |  |  |  |
| [4](#week-4) | Oct 5 | Planning | [📖](/tutorials/w04/tut04.html){.no-style target="_blank" aria-label="Tut 4 slides"} | [🖥️](/lecs/w04/lec04.html){.no-style target="_blank" aria-label="Lec 4 slides"} |  | [✍️](https://github.com/florianshkurti/csc477_fall22/blob/master/wall_following_assignment/CSC477_Assignment_1.pdf){.no-style target="_blank"} |  |
|  | Oct 12 | Reading Week |  |  |  |  |  |
| [5](#week-5) | Oct 19 | Linear Quadratic Regulator (LQR) |  | [🖥️](/lecs/w05/lec05.html){.no-style target="_blank" aria-label="Lec 5 slides"} | [📋](https://github.com/florianshkurti/comp417/tree/master/lqr_examples/python){.no-style target="_blank"} |  |  |
| [6](#week-6) | Oct 26 | Map Representations and Map Alignment |  | [🖥️](/lecs/w06/lec06.html){.no-style target="_blank" aria-label="Lec 6 slides"} |  |  |  |
|  |  | Occupancy Grid Mapping With Known Robot Poses |  |  |  |  |  |
| [7](#week-7) | Nov 2 | Maximum Likelihood, Least Squares Estimation, Maximum A Posteriori Estimation |  | [🖥️](/lecs/w07/lec07.html){.no-style target="_blank" aria-label="Lec 7 slides"} |  | [✍️](https://github.com/florianshkurti/csc477_fall22/blob/master/path_planning_and_control_assignment/description/CSC477_Assignment_2.pdf){.no-style target="_blank"} |  |
|  |  | GraphSLAM |  |  |  |  |  |
| [8](#week-8) | Nov 9 | Kalman Filter |  | [🖥️](/lecs/w08/lec08.html){.no-style target="_blank" aria-label="Lec 8 slides"} |  |  |  |
|  |  | Bayes' Filter and Kalman Filter |  |  |  |  |  |
| [9](#week-9) | Nov 16 | Extended Kalman Filter (EKF) | [📖](https://github.com/florianshkurti/csc477_fall22/blob/master/website/tutorials/Kalman_Filter_Notes.pdf){.no-style target="_blank" aria-label="Tut 9 Notes"} | [🖥️](/lecs/w09/lec09.html){.no-style target="_blank" aria-label="Lec 9 slides"} | [📋](https://github.com/florianshkurti/comp417/tree/master/filtering_examples/python){.no-style target="_blank"} |  |  |
| [10](#week-10) | Nov 23 | Particle Filter |  | [🖥️](/lecs/w10/lec10.html){.no-style target="_blank" aria-label="Lec 10 slides"} |  | [✍️](https://github.com/florianshkurti/csc477_fall22/blob/master/estimation_assignment/latex/CSC477_Assignment_3.pdf){.no-style target="_blank"} |  |
| [11](#week-11) | Nov 30 | Camera Optics and Multi-view Geometry |  | [🖥️](/lecs/w11/lec11.html){.no-style target="_blank" aria-label="Lec 11 slides"} |  |  |  |
| [12](#week-12) | Dec 7 | Visual odometry and Visual SLAM |  | [🖥️](/lecs/w11/lec11.html){.no-style target="_blank" aria-label="Lec 11 slides"} |  | [✍️](https://github.com/florianshkurti/csc477_fall22/blob/master/estimation_and_vision_assignment/latex/CSC477_Assignment_4.pdf){.no-style target="_blank"} |  |
| [13](#week-13) | Dec 8 | Study break, beginning of exams |  |  |  |  | [📂](https://www.cs.toronto.edu/~florian/courses/csc477_fall22/CSC2630_Project_Guidelines.pdf){.no-style target="_blank"}  |
:::


### Week 1 {#week-1}

**Introduction** \
Motivation, logistics, rough description of assignments, sense-plan-act paradigm.

**Sensors and Actuators** \
Camera, LiDAR, tactile, IMU, depth, GPS, Hall-effect sensors, encoders, RGBD. Pulse-Width Modulation. Motors.

**No Tutorials**

[**Slide**](/lecs/w01/lec01.html)

**Readings** \
- Dudek & Jenkin 3.1.1,4, 3.2-3, 4.1-8, 4.10, 5.1.1 \
- Optional: [Mike Langer's notes](http://www.cim.mcgill.ca/%7Elanger/558/1-imageprojection.pdf)


### Week 2 {#week-2}

**Kinematics** \
Frames of reference. Rotation representations. Homogeneous coordinates and transformations. Rigid body motion.

**Dynamics** \
Dynamical systems and control. Examples: Dubins car, differential drive car, unicycle, pendulum, cartpole, quadcopter. Holonomic vs. non-holonomic systems.

**Tutorial** : [Intro to ROS](/tutorials/w02/tut02.html)

[**Slide**](/lecs/w02/lec02.html)

**Readings** \
- [Paul Furgale: robot pose](http://paulfurgale.info/news/2014/6/9/representing-robot-pose-the-good-the-bad-and-the-ugly) \
- [Lavalle 13.1](http://msl.cs.uiuc.edu/planning/node657.html) \
- Dudek & Jenkin 3.1.5,6


### Week 3 {#week-3}
**PID Control** \
Tuning, cascading PID, advantages and drawbacks.

**Artificial Potential Fields and Obstacle Avoidance** \
Implementation issues, navigation functions. Vector-field histogram (VFH), dynamic window approach (DWA).

**Tutorial** : [Linear algebra refresher](/tutorials/w03/tut03.html)

[**Slide**](/lecs/w03/lec03.html)

**Readings** \
- Optional: [Astrom and Hagglund, Ch. 2](https://www.amazon.com/Automatic-Tuning-Controllers-Karl-Astrom/dp/1556170815) \
- [Lavalle Ch. 8.4](http://planning.cs.uiuc.edu/node388.html) \
- Dudek & Jenkin 6.3.4 \
- Optional: [Howie Choset's notes](http://www.cs.cmu.edu/~motionplanning/lecture/Chap4-Potential-Field_howie.pdf)


### Week 4 {#week-4}
**Planning** \
Dijkstra, A*, Rapidly-exploring Random Trees (RRT), Probabilistic RoadMaps (PRM)

**Tutorial** : [Probability refresher](/tutorials/w04/tut04.html)

[**Slide**](/lecs/w04/lec04.html)

**Readings** \
- [Blog post on A*](http://theory.stanford.edu/~amitp/GameProgramming/AStarComparison.html) \
- [Udacity Lesson 4](https://www.udacity.com/course/artificial-intelligence-for-robotics--cs373) \
- [Lavalle 5.5, 5.6](http://planning.cs.uiuc.edu/ch5.pdf)

### Week 5 {#week-5}

**Linear Quadratic Regulator (LQR)** \
Computing optimal actions for linear dynamical systems with quadratic cost-to-go functions.

**Tutorial** : Intro to numpy, Implementing LQR

[**Slide**](/lecs/w05/lec05.html)

**Readings** \
- Optional: Stephen Boyd's LQR [notes](https://stanford.edu/class/ee363/lectures/dlqr.pdf) and [examples](https://stanford.edu/class/ee103/lectures/control/control_slides.pdf)



### Week 6 {#week-6}

**Map Representations and Map Alignment** \
Occupancy grids, Octrees, Voronoi Graph, Homotopy Classes. Map alignment with known or unknown correspondences. Iterative Closest Point (ICP).

**Occupancy Grid Mapping With Known Robot Poses** \
Log-odds ratio, Probabilistic dynamics and measurement models, Bayesian estimation.

**Tutorial** : Derivations for occupancy grid mapping

[**Slide**](/lecs/w06/lec06.html)

**Readings** \
- [Pieter Abbeel's notes](https://people.eecs.berkeley.edu/~pabbeel/cs287-fa13/slides/ScanMatching.pdf) \
- [Pieter Abbeel's notes](https://people.eecs.berkeley.edu/~pabbeel/cs287-fa13/slides/MappingWithKnownPoses.pdf) \
- Probabilistic Robotics Ch. 2 and Ch. 9

### Week 7 {#week-7}

**Maximum Likelihood, Least Squares Estimation, Maximum A Posteriori Estimation** \
Least squares as a special case of maximum likelihood estimation on Gaussian models.

**GraphSLAM** \
Expectation and Covariance. Geometric interpretation of the covariance matrix. Nonlinear Least Squares formulation of the Simultaneous Localization And Mapping (SLAM) problem.

**Tutorial** : Demonstrating gMapping

[**Slide**](/lecs/w07/lec07.html)

**Readings** \
- [Udacity Lesson 6](https://www.udacity.com/school/artificial-intelligence) \
- Probabilistic Robotics Ch. 11


### Week 8 {#week-8}

**Kalman Filter** \
Bayes' rule on Gaussian distributions. Example of 1D Kalman Filter.

**Bayes' Filter and Kalman Filter** \
Kalman Filter as a special case of Bayes' Filter. Examples of 2D and 4D Kalman Filter. General prediction and update equations.

**Tutorial** : 

[**Slide**](/lecs/w08/lec08.html)

**Readings** \
- [Udacity Lesson 2](https://www.udacity.com/course/artificial-intelligence-for-robotics--cs373) \
- [Kalman Filter, Illustrated,](http://www.bzarg.com/p/how-a-kalman-filter-works-in-pictures/) \
- Probabilistic Robotics Ch. 2,3

### Week 9 {#week-9}

**Extended Kalman Filter (EKF)** \
Bayes' Filter and nonlinear transformations. Monte Carlo sampling vs. Linearization. EKF prediction and update equations. Examples: EKF Localization and EKF SLAM.

**Tutorial** : [Basic Kalman Filter implementation](https://github.com/florianshkurti/comp417/tree/master/filtering_examples/python), [Kalman Filter Summary Notes](https://github.com/florianshkurti/csc477_fall22/tree/master/website/tutorials/Kalman_Filter_Notes.pdf)

[**Slide**](/lecs/w09/lec09.html)

**Readings** \
- [Cyrill Stachniss' intro to EKF](https://www.youtube.com/watch?v=DE6Jn2cB4J4) \
- [Cyrill Stachniss' intro to EKF-SLAM](https://www.youtube.com/watch?v=XeWG5D71gC0) \
- Probabilistic Robotics Ch. 2,3


### Week 10 {#week-10}
**Particle Filter** \
Representing multimodal distributions. Particle propagation and resampling. Pathologies of particle filter. Importance Sampling. Examples: Markov localization in a known map. FastSLAM.

[**Slide**](/lecs/w10/lec10.html)

**Readings** \
- [Udacity Lesson 3](https://www.udacity.com/course/artificial-intelligence-for-robotics--cs373) \
- Optional: [Thrun's paper on PF](http://robots.stanford.edu/papers/thrun.pf-in-robotics-uai02.pdf)


### Week 11 {#week-11}

**Camera Optics and Multi-view Geometry** \
Pinhole cameras, lenses, perspective projection. Aperture, focal length, exposure time, depth-of-field. Structure from Motion.

**Tutorial** : 

[**Slide**](/lecs/w11/lec11.html)

**Readings** \
- Optional: [James Tompkin's notes.](https://www.cs.toronto.edu/lectures_Spring2017/11_Spring2017_CamerasAndOptics.pdf) \
- [Sanja Fidler's notes on depth from stereo](http://www.cs.toronto.edu/~fidler/slides/2017/CSC420/lecture12.pdf)


### Week 12 {#week-12}

**Visual odometry and Visual SLAM** \
Epipolar constraints. Depth from stereo disparity for parallel cameras. Triangulation as a least-squares problem. Scale issues in visual odometry with a single camera. Visual SLAM vs. structure from motion.

**Tutorial** : 

[**Slide**](/lecs/w11/lec11.html)

**Readings** \
- Optional: James Tompkin's notes on [stereo](http://cs.brown.edu/courses/cs143/lectures_Spring2017/12_Spring2017_StereoIntroduction.pdf) and [SfM](http://cs.brown.edu/courses/cs143/lectures_Spring2017/14_Spring2017_EpipolarGeometryAndStructureFromMotion.pdf). \
- [Sanja Fidler's notes on depth from stereo](http://www.cs.toronto.edu/~fidler/slides/2017/CSC420/lecture12.pdf)


### Week 13 {#week-13}

Study break, beginning of exams

Review for final exam