---
title: "Fall 2024 - UTM - CSC 413: Neural Networks and Deep Learning"
---

### Course Overview

It is very hard to hand-design programs to solve many real-world problems, e.g. distinguishing images of cats v.s. dogs. Machine learning algorithms allow computers to learn from example data, and produce a program that does the job. Neural networks are a class of machine learning algorithms originally inspired by the brain, but which have recently have seen a lot of success at practical applications. They're at the heart of production systems at companies like Google and Facebook for image processing, speech-to-text, and language understanding.

This course gives an overview of both the foundational ideas and the recent advances in neural net algorithms. Roughly the first 2/3 of the course focuses on supervised learning - training the network to produce a specified behavior when one has lots of labeled examples of that behavior. The last 1/3 focuses on unsupervised learning.

### Prerequisites

Prerequisite: CSC311H5 or CSC411H5\
Exclusion: CSC321H5 or CSC321H1 or CSC413H1 or CSC421H1 (SCI)\
Distribution Requirement: SCI

Students who lack a pre/co-requisite can be removed at any time unless they have received an explicit waiver from the department. The waiver form can be downloaded from [here](https://www.utm.utoronto.ca/math-cs-stats/undergraduate-students/forms).

### Course Delivery Details

| Lectures | Prof               | Day       | Time               | Location |
|----------|--------------------|-----------|--------------------|----------|
| LEC0101  | Igor Gilitschenski | Tuesday   | 5:00 pm - 7:00 pm  | MN3190   |
| LEC0102  | Florian Shkurti    | Wednesday | 11:00 am - 1:00 pm | MN3190   |

| Tutorials/Labs | Day    | Time                | Location |
|----------------|--------|---------------------|----------|
| PRA0101        | Friday | 10:00 am - 11:00 am | DH2020   |
| PRA0102        | Friday | 11:00 am - 12:00 pm | DH2020   |
| PRA0103        | Friday | 12:00 pm - 1:00 pm  | DH2020   |

-   Announcements will be posted on Quercus
-   Discussions will take place on Piazza
-   Zoom recordings will be posted on Quercus after lectures