all: lec01.html lec02.html lec03.html lec04.html lec05.html lec06.html lec07.html

lec01.html: w01/lec01.qmd
	cd w01 && quarto render lec01.qmd

lec02.html: w02/lec02.qmd
	cd w02 && quarto render lec02.qmd

lec03.html: w03/lec03.qmd
	cd w03 && quarto render lec03.qmd

lec04.html: w04/lec04.qmd
	cd w04 && quarto render lec04.qmd

lec05.html: w05/lec05.qmd
	cd w05 && quarto render lec05.qmd

lec06.html: w06/lec06.qmd
	cd w06 && quarto render lec06.qmd

lec07.html: w07/lec07.qmd
	cd w07 && quarto render lec07.qmd